name: Build and Deploy Chatbot Container

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to Azure Container Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.ACR_LOGIN_SERVER }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.ACR_LOGIN_SERVER }}/medical-chatbot:latest
    
    - name: Set up Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Deploy to Azure Container Instances
      uses: azure/CLI@v1
      with:
        inlineScript: |
          echo "Resource Group: ${{ secrets.ACI_RESOURCE_GROUP }}"
          echo "ACR Server: ${{ secrets.ACR_LOGIN_SERVER }}"
          echo "List available resource groups:"
          az group list --query "[].name" -o tsv
          echo "Running container creation with explicit scope..."
          
          # Set the resource group explicitly
          RG="${{ secrets.ACI_RESOURCE_GROUP }}"
          SUBSCRIPTION="6d8c61e2-99c2-48f5-b703-2239b7182b79"
          
          # Create container with explicitly defined resource ID
          az container create \
            --resource-group "$RG" \
            --name "medical-chatbot" \
            --image "${{ secrets.ACR_LOGIN_SERVER }}/medical-chatbot:latest" \
            --registry-login-server "${{ secrets.ACR_LOGIN_SERVER }}" \
            --registry-username "${{ secrets.ACR_USERNAME }}" \
            --registry-password "${{ secrets.ACR_PASSWORD }}" \
            --dns-name-label "careescapes-chatbot" \
            --ports 8000 \
            --environment-variables \
              AZURE_OPENAI_API_KEY="${{ secrets.AZURE_OPENAI_API_KEY }}" \
              AZURE_OPENAI_API_VERSION="${{ secrets.AZURE_OPENAI_API_VERSION }}" \
              AZURE_OPENAI_ENDPOINT="${{ secrets.AZURE_OPENAI_ENDPOINT }}" \
              AZURE_OPENAI_DEPLOYMENT="${{ secrets.AZURE_OPENAI_DEPLOYMENT }}" \
              REDIS_URL="${{ secrets.REDIS_URL }}"
    
    - name: Output Container Instance URL
      run: echo "Chatbot API deployed to http://careescapes-chatbot.${{ secrets.ACI_REGION }}.azurecontainer.io:8000" 