name: Frontend CI/CD
on:
  push:
    branches: [ main ]
    paths:
      - 'medical-chatbot-frontend/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          
      - name: Install Dependencies
        run: |
          cd medical-chatbot-frontend
          npm install
          
      - name: Build
        run: |
          cd medical-chatbot-frontend
          npm run build
          
      - name: Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "medical-chatbot-frontend"
          output_location: "build" 